# Generated by Django 4.1.5 on 2023-02-06 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unlv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='fk_topic_id',
            new_name='topic_id',
        ),
    ]
